### ISSUE TITLE
action fails due to missing render.R

### ISSUE THREAD

**Issue by aghaynes** [lucharo/rmarkdown-action#3]
Hi, 
I just tried to use your action but it failed due the render.R file being missing...
![grafik](https://user-images.githubusercontent.com/6594028/131458308-7b516c56-7f7b-4bb5-8910-49648b7b137d.png)
Any idea where it might be going wrong?

**Comment by rvalavi** [comment]
A similar issue for me! The `render.R` is available in the repo but when using the action it just does not recognize it!

**Comment by lucharo** [comment]
I will have a look very soon! Thanks for pointing out the issue :)

Luis Chaves
________________________________

**Comment by rvalavi** [comment]
Thanks a lot @lucharo!
I guess it's because the docker container does not have access to the `render.R` file. Maybe adding a `volume` or copying the file to the image would solve it!
